services:
  search-ui:
    build: .
    container_name: search-ui
    ports:
      - "3000:80"
    environment:
      - REACT_APP_ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - appnet

networks:
  appnet:
    external: true
